/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.promanage.ui;

import com.promanage.util.DBHelper;
import com.promanage.util.LanguageManager;
import java.awt.event.*;
import java.sql.*;
import java.util.ResourceBundle;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class DashboardFrame extends javax.swing.JFrame {

    private String username;
    private TaskFrame taskframe;
//    private int userId;

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame(String username, TaskFrame taskframe) {
        initComponents();
        setLocationRelativeTo(null);
        this.username = username;
        this.taskframe = taskframe;
        updateTexts();
        tblProjects.setDefaultEditor(Object.class, null);
        tblProjects.addMouseListener(new MouseAdapter() {
        });

        loadProjects();
    }

    DashboardFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void updateTexts() {
        ResourceBundle bundle = LanguageManager.getBundle();

        setTitle(bundle.getString("DashboardFrame.title"));
        lblWelcome.setText(bundle.getString("DashboardFrame.welcome") + ", " + username);
        btnLogout.setText(bundle.getString("DashboardFrame.btnLogout"));
        btnAddProject.setText(bundle.getString("DashboardFrame.btnAddProject"));
        btnEditProject.setText(bundle.getString("DashboardFrame.btnEditProject"));
        btnOpenProject.setText(bundle.getString("DashboardFrame.btnOpenProject"));
        btnDeleteProject.setText(bundle.getString("DashboardFrame.btnDeleteProject"));

        DefaultTableModel model = (DefaultTableModel) tblProjects.getModel();
        model.setColumnIdentifiers(new String[]{
            bundle.getString("DashboardFrame.tblProjects.id"),
            bundle.getString("DashboardFrame.tblProjects.name"),
            bundle.getString("DashboardFrame.tblProjects.desc"),
            bundle.getString("DashboardFrame.tblProjects.created_at")
        });
    }

    void loadProjects() {
        ResourceBundle bundle = LanguageManager.getBundle();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            bundle.getString("DashboardFrame.tblProjects.id"),
            bundle.getString("DashboardFrame.tblProjects.name"),
            bundle.getString("DashboardFrame.tblProjects.desc"),
            bundle.getString("DashboardFrame.tblProjects.created_at")
        });
        tblProjects.setModel(model);

        try (Connection conn = DBHelper.getConnection()) {
            String sql = "SELECT id, name, description, created_at FROM projects WHERE user_id = (SELECT id FROM users WHERE username = ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getString("description"),
                    rs.getTimestamp("created_at")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.project_delete_failed"),
                    bundle.getString("DashboardFrame.msg.error"), JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnOpenProject = new javax.swing.JButton();
        btnDeleteProject = new javax.swing.JButton();
        btnEditProject = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrollPaneProjects = new javax.swing.JScrollPane();
        tblProjects = new javax.swing.JTable();
        btnAddProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lblWelcome.setForeground(new java.awt.Color(204, 204, 204));
        lblWelcome.setText("Wellcome!");

        btnLogout.setBackground(new java.awt.Color(0, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnLogout))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnOpenProject.setBackground(new java.awt.Color(153, 153, 153));
        btnOpenProject.setText("Open Project");
        btnOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenProjectActionPerformed(evt);
            }
        });

        btnDeleteProject.setBackground(new java.awt.Color(153, 153, 153));
        btnDeleteProject.setText("Delete Project");
        btnDeleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProjectActionPerformed(evt);
            }
        });

        btnEditProject.setBackground(new java.awt.Color(153, 153, 153));
        btnEditProject.setText("Edit Project");
        btnEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnOpenProject)
                .addGap(52, 52, 52)
                .addComponent(btnDeleteProject)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenProject)
                    .addComponent(btnDeleteProject)
                    .addComponent(btnEditProject))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tblProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjectsMouseClicked(evt);
            }
        });
        scrollPaneProjects.setViewportView(tblProjects);

        btnAddProject.setBackground(new java.awt.Color(153, 255, 153));
        btnAddProject.setText("Add Project");
        btnAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnAddProject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddProject)
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProjectActionPerformed
        this.setVisible(false);
        new AddProjectFrame(username, this).setVisible(true);
    }//GEN-LAST:event_btnAddProjectActionPerformed

    private void tblProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectsMouseClicked
        int row = tblProjects.getSelectedRow();
        if (row != -1) {
            String projectName = tblProjects.getValueAt(row, 1).toString();
            System.out.println("Proyek yang diklik: " + projectName);
        }
    }//GEN-LAST:event_tblProjectsMouseClicked

    private void btnDeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProjectActionPerformed
        ResourceBundle bundle = LanguageManager.getBundle();
        int selectedRow = tblProjects.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.select_delete"),
                    bundle.getString("DashboardFrame.msg.warning"), JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                bundle.getString("DashboardFrame.msg.confirm_delete"),
                bundle.getString("DashboardFrame.msg.confirm"), JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            int projectId = (int) tblProjects.getValueAt(selectedRow, 0);

            try (Connection conn = DBHelper.getConnection()) {
                String sql = "DELETE FROM projects WHERE id = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1, projectId);
                stmt.executeUpdate();

                JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.project_deleted"));
                loadProjects();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.project_delete_failed"),
                        bundle.getString("DashboardFrame.msg.error"), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteProjectActionPerformed

    private void btnEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProjectActionPerformed
        ResourceBundle bundle = LanguageManager.getBundle();
        int selectedRow = tblProjects.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.select_edit"),
                    bundle.getString("DashboardFrame.msg.warning"), JOptionPane.WARNING_MESSAGE);
            return;
        }

        int projectId = (int) tblProjects.getValueAt(selectedRow, 0);
        String currentName = tblProjects.getValueAt(selectedRow, 1).toString();
        String currentDesc = tblProjects.getValueAt(selectedRow, 2).toString();

        new EditProjectFrame(projectId, currentName, currentDesc, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditProjectActionPerformed

    private void btnOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenProjectActionPerformed
        ResourceBundle bundle = LanguageManager.getBundle();
        int selectedRow = tblProjects.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, bundle.getString("DashboardFrame.msg.select_open"),
                    bundle.getString("DashboardFrame.msg.warning"), JOptionPane.WARNING_MESSAGE);
            return;
        }

        int projectId = (int) tblProjects.getValueAt(selectedRow, 0);
        this.setVisible(false);
        new TaskFrame(projectId, this).setVisible(true);
    }//GEN-LAST:event_btnOpenProjectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProject;
    private javax.swing.JButton btnDeleteProject;
    private javax.swing.JButton btnEditProject;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOpenProject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JScrollPane scrollPaneProjects;
    private javax.swing.JTable tblProjects;
    // End of variables declaration//GEN-END:variables

}
