/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.promanage.ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.promanage.util.CryptoUtil;
import com.promanage.util.DBHelper;
import javax.swing.JOptionPane;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 *
 * @author ACER
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    private Locale currentLocale;
    private ResourceBundle resourceBundle;
    private boolean isChangingLanguage = false;

    public RegisterFrame() {
        initComponents();
        setLocationRelativeTo(null);
        cbLanguage.setSelectedIndex(0);
        applyLanguage();
        System.out.println("lblUsername after apply = " + lblNewUsername.getText());
    }

    private void applyLanguage() {
        isChangingLanguage = true;

        int selectedLang = cbLanguage.getSelectedIndex();
        String language = (selectedLang == 1) ? "id" : "en";
        String country = (selectedLang == 1) ? "ID" : "US";

        currentLocale = new Locale(language, country);
        try {
            resourceBundle = ResourceBundle.getBundle("com.promanage.i18n.Bundle", currentLocale);

            // Debug: Periksa apakah ResourceBundle dimuat dengan benar
            System.out.println("ResourceBundle dimuat untuk lokal: " + currentLocale);

            // Set teks label dan tombol
            lblRegisterTitle.setText(resourceBundle.getString("RegisterFrame.lblRegisterTitle.text"));
            lblNewUsername.setText(resourceBundle.getString("RegisterFrame.lblNewUsername.text"));
            lblNewPassword.setText(resourceBundle.getString("RegisterFrame.lblNewPassword.text"));
            btnToLogin.setText(resourceBundle.getString("RegisterFrame.btnToLogin.text"));
            btnRegister.setText(resourceBundle.getString("RegisterFrame.btnRegister.text"));
            lblRegisterError.setText("");

            // Perbarui model combobox tanpa memicu pendengar tindakan
            String[] langs = {
                resourceBundle.getString("RegisterFrame.cbLanguage.0"),
                resourceBundle.getString("RegisterFrame.cbLanguage.1")
            };
            cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(langs));
            cbLanguage.setSelectedIndex(selectedLang);

            // Paksa repaint keseluruhan frame
            this.repaint();
        } catch (MissingResourceException e) {
            System.err.println("Sumber daya hilang: " + e.getKey());
            e.printStackTrace();
        }

        isChangingLanguage = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegisterTitle = new javax.swing.JLabel();
        cbLanguage = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblNewUsername = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnToLogin = new javax.swing.JButton();
        lblRegisterError = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lblRegisterTitle.setText("REGISTER");

        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Indonesia" }));
        cbLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanguageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRegisterTitle)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblRegisterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblNewUsername.setText("Username");

        lblNewPassword.setText("Password");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnToLogin.setText("Login");
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });

        lblRegisterError.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(btnToLogin)
                .addGap(52, 52, 52)
                .addComponent(btnRegister)
                .addGap(108, 108, 108))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewUsername)
                            .addComponent(lblNewPassword))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewUsername)
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegisterError)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUsername)
                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnToLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblRegisterError)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String username = txtNewUsername.getText();
        String password = new String(txtNewPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            lblRegisterError.setText(resourceBundle.getString("RegisterFrame.register.required"));
            return;
        }

        try (Connection conn = DBHelper.getConnection()) {
            // Cek apakah username sudah ada
            String checkQuery = "SELECT COUNT(*) FROM users WHERE username = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            checkStmt.setString(1, username);
            ResultSet rs = checkStmt.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                lblRegisterError.setText(resourceBundle.getString("RegisterFrame.register.username_exists"));
                return;
            }

            // Hash password + salt
            String salt = CryptoUtil.generateSalt();
            String hash = CryptoUtil.hashPassword(password, salt);
            String hashWithSalt = hash + ":" + salt;

            // Simpan user
            String insertQuery = "INSERT INTO users (username, password_hash) VALUES (?, ?)";
            PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
            insertStmt.setString(1, username);
            insertStmt.setString(2, hashWithSalt);
            insertStmt.executeUpdate();

            lblRegisterError.setText(resourceBundle.getString("RegisterFrame.register.success"));
            JOptionPane.showMessageDialog(this, resourceBundle.getString("RegisterFrame.register.success_message"),
                    "Info", JOptionPane.INFORMATION_MESSAGE);

            // Opsional: kembali ke LoginFrame
            this.dispose();
            new LoginFrame().setVisible(true);

        } catch (Exception e) {
            lblRegisterError.setText(resourceBundle.getString("RegisterFrame.register.error"));
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed
        this.dispose(); // Tutup RegisterFrame
        new LoginFrame().setVisible(true); // Buka LoginFrame
    }//GEN-LAST:event_btnToLoginActionPerformed

    private void cbLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanguageActionPerformed
        if (!isChangingLanguage) {
            System.out.println("Mengubah bahasa...");
            applyLanguage();
        }
    }//GEN-LAST:event_cbLanguageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNewUsername;
    private javax.swing.JLabel lblRegisterError;
    private javax.swing.JLabel lblRegisterTitle;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtNewUsername;
    // End of variables declaration//GEN-END:variables
}
